name: Android

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  android:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - android-26
          - android-27
        abi:
          - armeabi-v7a
          - arm64-v8a
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: cmake -H$GITHUB_WORKSPACE -B$GITHUB_WORKSPACE/build -GNinja -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=${{ matrix.abi }} -DANDROID_PLATFORM=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - run: cmake --build $GITHUB_WORKSPACE/build
