name: Linux

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-9
          - g++-10
          - g++-11
          - g++-12
          - clang++-13
          - clang++-14
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-old:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang++-7
          - clang++-8
          - clang++-9
          - clang++-10
          - clang++-11
          - clang++-12
        build_type: [Debug, Release]

    runs-on: ubuntu-20.04

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - run: sudo apt-get update -y

    - run: sudo apt-get install -y ${{ matrix.compiler }}

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-clang-extra:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      CXX: clang++

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="-fms-extensions"

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure
