name: Linux

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-7
          - g++-8
          - g++-9
          - g++-10
          - clang++-8
          - clang++-9
          - clang++-10
        build_type: [Debug, Release]

    runs-on: ubuntu-20.04

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  linux-clang-extra:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: ubuntu-20.04

    env:
      CXX: clang++

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="-fms-extensions"

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

  clang-conanio:
    strategy:
      fail-fast: false
      matrix:
        image:
          # List: https://github.com/conan-io/conan-docker-tools
          - clang60
          - clang7
          - clang9-x86
          - clang11
        build_type: [Debug, Release]

    container:
      image: conanio/${{ matrix.image }}
      options: --user root

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - run: |
       apt-get update
       apt-get -qq install -y --no-install-recommends software-properties-common
       add-apt-repository ppa:git-core/ppa -y
       apt-get -qq update
       apt-get -qq upgrade -y git

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure
