name: macOS

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  xcode:
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: 11
            build_type: Debug
            os: macos-11
          - xcode: 11
            build_type: Release
            os: macos-11
          - xcode: 12
            build_type: Debug
            os: macos-11
          - xcode: 12
            build_type: Release
            os: macos-11
          - xcode: 13
            build_type: Debug
            os: macos-12
          - xcode: 13
            build_type: Release
            os: macos-12
          - xcode: 14
            build_type: Debug
            os: macos-12
          - xcode: 14
            build_type: Release
            os: macos-12
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE

    - working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - working-directory: build/
      run: ctest --config ${{ matrix.build_type }} --output-on-failure
