name: macOS

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'doc/**'

jobs:
  xcode:
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: 14
            build_type: Release
            os: macos-13
          - xcode: 15
            build_type: Release
            os: macos-14
          - xcode: 16
            build_type: Release
            os: macos-15
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Ninja
      run: brew install ninja

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure
