name: Sanitizer

on: [push, pull_request]

jobs:
  sanitizer:
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++, clang++]
        sanitizer: [address, undefined]

    runs-on: ubuntu-20.04

    env:
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DTAOCPP_JSON_BUILD_EXAMPLES=OFF -DCMAKE_CXX_FLAGS="-fsanitize=${{ matrix.sanitizer }}"

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure
